use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'FlagKits_Example' do
  pod 'FlagKits', :path => '../'
  pod 'IQKeyboardManagerSwift'
  
  target 'FlagKits_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.1'
            config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
    end
end
