# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: swift
xcode_workspace: Example/FlagKits.xcworkspace
xcode_project: Example/FlagKits.xcodeproj
xcode_scheme: FlagKits-Example
cache: cocoapods
podfile: Example/Podfile
script:
- set -o pipefail && xcodebuild test -workspace Example/FlagKits.xcworkspace -scheme FlagKits-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
