# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
env:
  - DESTINATION="OS=10.2,name=iPhone 7" SCHEME="FlagKits-Example" SDK=iphonesimulator
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - cd Example
# xcode_workspace: Example/FlagKits.xcworkspace
# xcode_project: Example/FlagKits.xcodeproj
# xcode_scheme: FlagKits-Example
cache: cocoapods
podfile: Example/Podfile
script:
  - pod update
  - set -o pipefail
  - xcodebuild -workspace Example/FlagKits.xcworkspace -scheme "FlagKits-Example" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild test -workspace Example/FlagKits.xcworkspace -scheme "FlagKits-Example" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - pod lib lint
